# Generated by Django 6.1.1 on 2026-09-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bun_unit_price', models.DecimalField(decimal_places=2, default=22.883, max_digits=10)),
                ('egg_unit_price', models.DecimalField(decimal_places=2, default=13.543, max_digits=10)),
                ('banana_unit_price', models.DecimalField(decimal_places=2, default=9.807, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
