# Generated by Django 6.1.1 on 2026-09-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_foodprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodPrice',
        ),
    ]
