# Generated by Django 6.1.1 on 2026-09-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0002_holiday_created_at_alter_holiday_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationsetting',
            name='banana_per_student',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rationsetting',
            name='bun_per_student',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rationsetting',
            name='egg_per_student',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
