# Generated by Django 6.1.1 on 2026-09-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0003_alter_rationsetting_banana_per_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='chalan_photo',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='delivery',
            name='banana_chalan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='banana_chalan_image',
            field=models.ImageField(blank=True, null=True, upload_to='chalans/banana/'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='banana_chalan_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='bun_chalan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='bun_chalan_image',
            field=models.ImageField(blank=True, null=True, upload_to='chalans/bun/'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='bun_chalan_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='egg_chalan_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='egg_chalan_image',
            field=models.ImageField(blank=True, null=True, upload_to='chalans/egg/'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='egg_chalan_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='banana_delivered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='bun_delivered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='egg_delivered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
